# 一、多维数组对象（ndarray）


### 1. ndarray为同构数据多维容器

### 2. 当不同类型的元素构建ndarray会怎样？

In [1]:
import numpy as np
data = np.array(['hello', 123, 1.23])
print(data)

['hello' '123' '1.23']


### 3. 数组创建函数
<img src="image/array.png" style="width:500px;height:300;">

# 二、广播（broadcasting）

### 1. 广播指的是不同形状的数组之间的算术运算的执行方式

### 2. 显式表示向量为矩阵形式，有时可以避免难以觉察的bug

In [2]:
arr = np.random.randn(4, 3)
arr_mean = arr.mean(axis=0)
print(arr_mean.shape)

(3,)


In [3]:
arr = np.random.randn(4, 3)
arr_mean = arr.mean(axis=0, keepdims=True)
print(arr_mean.shape)

(1, 3)


In [4]:
arr = np.random.randn(4, 3)
arr_mean = arr.mean(axis=0)
print(arr_mean.reshape(1, 3).shape)

(1, 3)


### 3. “广播维”必须为1

# 三、索引

### 1. 数组切片与列表切片的区别？

In [5]:
lst = [1, 2, 3, 4, 5]
arr = np.array([1, 2, 3, 4, 5])

x = lst[1:3]
x[:] = [4, 4]
print(lst)
y = arr[1:3]
y[:] = 4 # 运用了广播
print(arr)

[1, 2, 3, 4, 5]
[1 4 4 4 5]


* 列表切片是原始列表的副本，数组切片是原始数组的视图

### 2. 切片索引

In [6]:
arr2d = np.arange(1, 10).reshape(3, 3)
print(arr2d)
print(arr2d[:2])
print(arr2d[:2, :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


* `arr2d[:2]`默认是沿着第0轴（最高维度轴）切片,在二维结构中即以行做切片

### 3. 布尔型索引

In [7]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
data = np.arange(1,13).reshape(4, 3)
print(data[names == 'Bob'])
print(data[names == 'Bob', :])
data[data < 7] = 0
print(data)

[[ 1  2  3]
 [10 11 12]]
[[ 1  2  3]
 [10 11 12]]
[[ 0  0  0]
 [ 0  0  0]
 [ 7  8  9]
 [10 11 12]]


* 与切片索引类似，默认沿着第0轴匹配

### 4. 花式索引

* 常用于在矩阵中以特定顺序选取行列子集

# 四、数组运算

### 1. 条件逻辑数组运算（np.where函数）

In [8]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
print(result)

[ 1.1  2.2  1.3  1.4  2.5]


* np.where函数是三元表达式x if condition else y的矢量化版本
* np.where函数是布尔型索引设置值的加强版本

# 五、线性代数
 

### 1. 通过 `*` 对两个二维数组相乘得到的是一个元素级的积，而不是一个矩阵内积

### 2. NumPy提供了一个用于矩阵乘法的`dot`函数（既是一个数组方法也是numpy命名空间中的一个函数）

### 3. 二维数组与合适大小的一维数组的矩阵点积运算？（output:二维数组?或一维数组?）

In [9]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = x.dot(np.ones(3))
z = x.dot(np.ones((3, 1)))
print(y)
print(z)

[  6.  15.]
[[  6.]
 [ 15.]]


* 所以显式表示向量为矩阵形式，有时可以避免难以觉察的bug

### 4. np.linalg矩阵运算库
<img src="image/linalg.png" style="width:500px;height:300;">